language: java
jdk:
 - oraclejdk8
addons:
  sonarqube:
    organization: "AlphaLeader" # the key of the org you chose at step #3
    token:
      secure: 5b17735859009b6ad66e7af710e9a7a424a04563 # encrypted value of your token
    branches:
      - master
      - Calvin-Mongo
install:
 - mvn -N io.takari:maven:wrapper
 - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
 # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
 # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
 - sonar-scanner