language: java
jdk:
 - oraclejdk8
install:
 - mvn -N io.takari:maven:wrapper
 - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
 # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
 # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
