language: java
jdk:
 - oraclejdk8
addons:
  sonarqube:
    organization: "308309" # the key of the org you chose at step #3
    token:
      secure: 5d8f23498479617e32a0a4cf16c3c41aeeb253b7 # encrypted value of your token
    branches:
      - master
      - Calvin-Mongo
install:
 - mvn -N io.takari:maven:wrapper
 - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
 # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
 # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
 - sonar-scanner